openapi: 3.0.0
info:
  title: Evalya Smart API
  version: 1.0.0
  description: API pour la plateforme de gestion des devoirs et examens

servers:
  - url: http://localhost:5001/api
    description: Serveur de développement

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
          description: Message d'erreur

    Devoir:
      type: object
      properties:
        id:
          type: integer
        titre:
          type: string
        classeId:
          type: integer
        matiereId:
          type: integer
        dateLimite:
          type: string
          format: date-time
        status:
          type: string
          enum: [draft, published, archived]

    SoumissionDevoir:
      type: object
      properties:
        id:
          type: integer
        devoir_id:
          type: integer
        eleve_id:
          type: integer
        fichier_url:
          type: string
        contenu_texte:
          type: string
        date_soumission:
          type: string
          format: date-time
        note:
          type: number
        commentaire:
          type: string

paths:
  /auth/login:
    post:
      summary: Authentification utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Connexion réussie
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  role:
                    type: string
        '401':
          description: Identifiants invalides
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /devoirs:
    get:
      summary: Liste des devoirs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Liste des devoirs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Devoir'
        '403':
          description: Accès non autorisé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Créer un nouveau devoir
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Devoir'
      responses:
        '201':
          description: Devoir créé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Devoir'
        '403':
          description: Accès non autorisé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /soumissions:
    post:
      summary: Soumettre un devoir
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                devoir_id:
                  type: integer
                fichier_url:
                  type: string
                contenu_texte:
                  type: string
      responses:
        '201':
          description: Soumission créée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SoumissionDevoir'
        '400':
          description: Erreur de validation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Accès non autorisé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      summary: Liste des soumissions
      security:
        - bearerAuth: []
      parameters:
        - name: devoirId
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: Liste des soumissions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SoumissionDevoir'
        '403':
          description: Accès non autorisé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 